version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  generate_study_population_pbc:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_pbc
    outputs:
      highly_sensitive:
        cohort: output/input_pbc.csv

  feasibility:
    run: stata-mp:latest analysis/feasibility.do
    needs: [generate_study_population, generate_study_population_pbc]
    outputs:
      moderately_sensitive:
        log: logs/feasibility.log
        table: output/tables/udca*.csv
        #table_oba: output/tables/oba*.csv
      
  extract_udca: 
    run: cohortextractor:latest generate_cohort --study-definition study_definition_additional
    needs: [generate_study_population_pbc]
    outputs:
      highly_sensitive:
        cohort: output/input_additional.csv

  prep_drug_data: 
    run: stata-mp:latest analysis/101_drug_prep.do
    needs: [extract_udca, generate_study_population_pbc]
    outputs:
      moderately_sensitive:
        log: logs/drug_prep.log
        drug_data: output/time_varying_udca*.dta

  drug_descriptives:
    run: stata-mp:latest analysis/102_udca_descriptives.do
    needs: [prep_drug_data, generate_study_population_pbc]
    outputs:
      moderately_sensitive:
        log: logs/udca_descriptives.log
        summary: output/tables/udca_descriptives.txt

  baseline_tables:
    run: stata-mp:latest analysis/103_baseline_tables.do
    needs: [generate_study_population_pbc]
    outputs:
      moderately_sensitive:
        log: logs/baseline_tables.log
        chars: output/tables/baseline*.csv
        meds: output/tables/additional*.csv

  analysis:
    run: stata-mp:latest analysis/104_propensity_score.do
    needs: [generate_study_population_pbc]
    outputs:
      moderately_sensitive:
        log: logs/propensity_score.log
        output: output/tables/covid*
        