version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  generate_study_population_pbc:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_pbc
    outputs:
      highly_sensitive:
        cohort: output/input_pbc.csv

  feasibility:
    run: stata-mp:latest analysis/feasibility.do
    needs: [generate_study_population, generate_study_population_pbc]
    outputs:
      moderately_sensitive:
        log: logs/feasibility.log
        table: output/tables/udca*.csv
        #table_oba: output/tables/oba*.csv
      
  extract_udca: 
    run: cohortextractor:latest generate_cohort --study-definition study_definition_additional
    needs: [generate_study_population_pbc]
    outputs:
      highly_sensitive:
        cohort: output/input_additional.csv

  prep_drug_data: 
    run: stata-mp:latest analysis/101_drug_prep.do
    needs: [extract_udca, generate_study_population_pbc]
    outputs:
      moderately_sensitive:
        log: logs/drug_prep.log
      highly_sensitive:
        drug_data: output/time_varying_udca*.dta

  drug_descriptives:
    run: stata-mp:latest analysis/102_udca_descriptives.do
    needs: [prep_drug_data, generate_study_population_pbc]
    outputs:
      moderately_sensitive:
        log: logs/udca_descriptives.log
        summary: output/tables/udca_descriptives.txt

  time_varying_prep:
    run: stata-mp:latest analysis/103_time_varying_prep.do
    needs: [generate_study_population_pbc, prep_drug_data]
    outputs:
      highly_sensitive:
        datasets: output/tv*.dta
        analysis: output/an_*.dta
      moderately_sensitive:
        log: logs/time_varying.log
        

  baseline_tables:
    run: stata-mp:latest analysis/104_baseline_tables.do
    needs: [generate_study_population_pbc]
    outputs:
      moderately_sensitive:
        log: logs/baseline_tables.log
        chars: output/tables/baseline*.csv
        meds: output/tables/additional*.csv

  analysis_plots:
    run: stata-mp:latest analysis/105_analysis_plots.do
    needs: [time_varying_prep]
    outputs:
      moderately_sensitive:
        log: logs/analysis.log
        chars: output/graphs/adjcurve*.csv

  analysis_models:
    run: stata-mp:latest analysis/106_analysis_models.do
    needs: [time_varying_prep]
    outputs:
      moderately_sensitive:
        log: logs/analysis_models.log
        
        