version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_flowchart:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_flowchart
    outputs:
      highly_sensitive:
        cohort: output/input_flowchart.csv

  generate_flowchart_stp:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_stp
    needs: [generate_study_population_flowchart]
    outputs:
      highly_sensitive:
        cohort: output/input_stp.csv

  flowchart_data:
    run: stata-mp:latest analysis/100_flowchart.do
    needs: [generate_study_population_flowchart, generate_study_population_pbc, generate_flowchart_stp]
    outputs:
      moderately_sensitive:
        log: logs/flowchart.log
        table: output/flowchart/values.txt

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  generate_study_population_pbc:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_pbc
    outputs:
      highly_sensitive:
        cohort: output/input_pbc.csv

  generate_study_population_vacc:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_vacc
    outputs:
      highly_sensitive:
        cohort: output/input_vacc.csv

  feasibility:
    run: stata-mp:latest analysis/feasibility.do
    needs: [generate_study_population, generate_study_population_pbc]
    outputs:
      moderately_sensitive:
        log: logs/feasibility.log
        table: output/tables/udca*.csv
        #table_oba: output/tables/oba*.csv
      
  extract_udca: 
    run: cohortextractor:latest generate_cohort --study-definition study_definition_additional
    needs: [generate_study_population_pbc]
    outputs:
      highly_sensitive:
        cohort: output/input_additional.csv

  extract_udca_vacc: 
    run: cohortextractor:latest generate_cohort --study-definition study_definition_addvacc
    needs: [generate_study_population_vacc]
    outputs:
      highly_sensitive:
        cohort: output/input_addvacc.csv


  prep_drug_data: 
    run: stata-mp:latest analysis/101_drug_prep.do
    needs: [extract_udca, generate_study_population_pbc, extract_udca_vacc, generate_study_population_vacc]
    outputs:
      moderately_sensitive:
        log: logs/drug_prep.log
      highly_sensitive:
        drug_data: output/time_varying_udca*.dta

  drug_descriptives:
    run: stata-mp:latest analysis/102_udca_descriptives.do
    needs: [prep_drug_data, generate_study_population_pbc]
    outputs:
      moderately_sensitive:
        summary: output/tables/udca_descriptives*.txt

  time_varying_prep:
    run: stata-mp:latest analysis/103_time_varying_prep.do
    needs: [generate_study_population_pbc, prep_drug_data, extract_udca_vacc, generate_study_population_vacc]
    outputs:
      highly_sensitive:
        datasets: output/tv*.dta
        analysis: output/an_*.dta
        

  baseline_tables:
    run: stata-mp:latest analysis/104_baseline_tables.do
    needs: [generate_study_population_pbc, generate_study_population_vacc, time_varying_prep]
    outputs:
      moderately_sensitive:
        chars: output/tables/baseline*.csv
        meds: output/tables/additional*.csv
      
  high_cost_drugs:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hc_drugs
    needs: [generate_study_population_pbc]
    outputs:
      highly_sensitive:
        cohort: output/input_hc_drugs.csv

  hcd_descriptives:
    run: stata-mp:latest analysis/104_a_hcd_descriptives.do
    needs: [high_cost_drugs, generate_study_population_pbc]
    outputs:
      highly_sensitive:
        bl_data: output/baseline_oca_n.dta
      moderately_sensitive:
        table: output/tables/baseline_oca*.csv
        
  analysis_plots:
    run: stata-mp:latest analysis/105_analysis_plots.do
    needs: [time_varying_prep]
    outputs:
      moderately_sensitive:
        log: logs/analysis.log
        chars: output/graphs/adjcurv*.svg
        table: output/tables/cum_incidence.txt

  analysis_models:
    run: stata-mp:latest analysis/106_analysis_models.do
    needs: [time_varying_prep, hcd_descriptives]
    outputs:
      moderately_sensitive:
        tables: output/tables/cox*.txt
        graphs: output/graphs/schoenplot*.svg
        km_plots: output/graphs/km*.svg